### ISSUE TITLE
Add Options for Date Range 

### ISSUE THREAD

**Issue by codeongit** [oleander/git-fame-rb#45]
something like  git blame --from=2016-05-09

**Comment by oleander** [comment]
I'll add it to my list of suggestions, thanks!

**Comment by oleander** [comment]
Just realized that they are discussed in #44 and #27.

**Comment by TafThorne** [comment]
The `git blame` data should take any file version ID, either revision key or dates.  The only additional work might be to ensure that we correctly discount any lines that were last changed before a date.  That probably has to be done whether or not this issue is looked at, although it does clarify that a date based approach is needed for issue #44 as well or instead of the revision key.
